<?php

/**
 * Created by PhpStorm.
 * User: Asus
 * Date: 8/28/2017
 * Time: 8:16 PM
 */
class Photo extends Db_objects
{
    protected static $db_table = "photos";
    protected static $db_table_fields_names = array('id', 'title', 'caption', 'description', 'filename', 'alternatetext', 'type', 'size');

    public $id;
    public $title;
    public $caption;
    public $description;
    public $filename;
    public $alternatetext;
    public $type;
    public $size;

    public $tmp_path;
    public $errors = array();

    public $upload_errors = array(
      UPLOAD_ERR_OK          => "There is no error, the file uploaded with success",
      UPLOAD_ERR_INI_SIZE    => "The uploaded file exceeds the upload_max_filesize directive in php.ini",
      UPLOAD_ERR_FORM_SIZE   => "The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form",
      UPLOAD_ERR_PARTIAL     => "The uploaded file was only partially uploaded",
      UPLOAD_ERR_NO_FILE     => "No file was uploaded",
      UPLOAD_ERR_NO_TMP_DIR  => "Missing a temporary folder.",
      UPLOAD_ERR_CANT_WRITE  => "Failed to write file to disk",
      UPLOAD_ERR_EXTENSION   => "A PHP extension stopped the file upload"
    );

    public function setFile($file){

        if (empty($file) || !$file || !is_array($file)){
            echo "Set file error 3";

            $this->errors[] = "There was no file uploaded here";
            return false;
        }elseif($file['error'] !=0){
            echo "Set file error 2";
            $this->errors[] = $this->upload_errors['error'];
            return false;
        }else{
             echo "Set file no error";
            $this->filename = basename($file['name']);
            $this->tmp_path = $file['tmp_name'];
            $this->type = $file['type'];
            $this->size = $file['size'];
        }


    }

    public function save()
    {
        if ($this->id){
            $this->update();
        }else{
            if (!empty($this->errors)){
                return false;
            }

            if(empty($this->filename) || empty($this->tmp_path)){
                $this->errors[] = "File was not available to upload.";
                return false;
            }

            $target_path = SITE_ROOT.DS.'ADMIN'.DS.$this->upload_directory.DS.$this->filename;

            if (file_exists($target_path)){

                $this->errors[] = "The file $this->tmp_path already exsits!!  ".$target_path;
                return false;
            }

            if (move_uploaded_file($this->tmp_path, $target_path)){

                if ($this->create()){
                    unset($this->tmp_path);
                    return true;
                }
            }else{
                $this->errors[] = "You donot have permission to write in the traget folder";
                return false;
            }

            //$this->create();


        }
        //return parent::save(); // TODO: Change the autogenerated stub
    }



    public function deletePhoto(){
        if($this->delete()){
            $path = SITE_ROOT.DS.'ADMIN'.DS.$this->picturePath();
            echo $path;
            return unlink($path) ? true : false;
        }else{

            return false;

        }
    }


}
?>

<!--\XAMPP\HTDOCS\PHOTOGALLERY\ADMIN\images\jungle1503931226.png
Warning: unlink(\XAMPP\HTDOCS\PHOTOGALLERY\ADMIN\images\jungle1503931226.png): No such file or directory in C:\xampp\htdocs\PhotoGallery\admin\includes\Photo.php on line 106

-->

