<?php

/**
 * Created by PhpStorm.
 * User: Asus
 * Date: 8/27/2017
 * Time: 2:13 PM
 */
class User extends Db_objects
{


//    Always delare veriable name according to database coulumn name
    protected static $db_table = "users";
    protected static $db_table_fields_names = array('username','password','firstname','lastname', 'filename');
    public $id;
    public $username;
    public $password;
    public $firstname;
    public $lastname;
    public $filename;

    public $tmp_path;



    /**
     * @param $attribute
     * @return bool
     */

    public static function verifyUser($username, $password){
       global $database;

       $username = $database->escapeString($username);
       $password = $database->escapeString($password);

       $sql = "SELECT * FROM ".self::$db_table." WHERE username = '$username' AND password = '$password' limit 1";
       //echo $sql;
       $result = self::findThisQuery($sql);

       return !empty($result) ? array_shift($result) : false; //http://php.net/manual/en/language.operators.comparison.php

    }

    public function deleteUser(){
        if($this->delete()){
            $path = SITE_ROOT.DS.'ADMIN'.DS.$this->picturePath();
            echo $path;
            return unlink($path) ? true : false;
        }else{

            return false;

        }
    }

    public function setFile($file){

        if (empty($file) || !$file || !is_array($file)){
            echo "Set file error 3";

            $this->errors[] = "There was no file uploaded here";
            return false;
        }elseif($file['error'] !=0){
            echo "Set file error 2";
            $this->errors[] = $this->upload_errors['error'];
            return false;
        }else{
            echo "Set file no error";
            $this->filename = basename($file['name']);
            $this->tmp_path = $file['tmp_name'];

        }


    }

    public function saveUser()
    {
        if ($this->id){
            $this->update();
        }else{
            if (!empty($this->errors)){
                return false;
            }

            if(empty($this->filename) || empty($this->tmp_path)){
                $this->errors[] = "File was not available to upload.";
                return false;
            }

            $target_path = SITE_ROOT.DS.'ADMIN'.DS.$this->upload_directory.DS.$this->filename;

            if (file_exists($target_path)){

                $this->errors[] = "The file $this->tmp_path already exsits!!  ".$target_path;
                return false;
            }

            if (move_uploaded_file($this->tmp_path, $target_path)){

                if ($this->create()){
                    unset($this->tmp_path);
                    return true;
                }
            }else{
                $this->errors[] = "You donot have permission to write in the traget folder";
                return false;
            }

            //$this->create();


        }
        //return parent::save(); // TODO: Change the autogenerated stub
    }


}